# Generated by Django 5.0.4 on 2024-04-19 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_category_food_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None), size=None),
        ),
    ]
