# Generated by Django 5.0.4 on 2024-04-22 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_food_types_food_option_1_food_option_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(default='default_image.jpg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.FileField(default='default_image.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_1_foods', to='food.option'),
        ),
        migrations.AlterField(
            model_name='food',
            name='option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_2_foods', to='food.option'),
        ),
        migrations.AlterField(
            model_name='food',
            name='option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_3_foods', to='food.option'),
        ),
    ]
